data:
  input_size: [224, 224]
  normalize: true
  dtype: float32

pipeline:
  cache: false
  shuffle: True
  shuffle_buffer_size: 512
  batch_size: 8
  drop_remainder: false
  prefetch: true

augment:
  flip_left_right: true
  flip_up_down: false
  random_crop: null
  brightness: null

train:
  epochs: 5
  learning_rate: 0.001
  optimizer: adam        # adam | sgd | rmsprop
  loss: sparse_categorical_crossentropy
  metrics: ["accuracy"]
  seed: 42
  mixed_precision: false
  strategy: auto         # auto | single | mirrored | tpu

model:
  architecture: EfficientNetV2B0
  weights: imagenet
  num_classes: 120
  drop_rate: 0.5
  freeze_backbone: true